lamp:
  swagger:
    license: Apache 2.0
    licenseUrl: ''
    termsOfServiceUrl: ''
    version: '@project.version@'
    contact: # 联系人信息
      url: ''
      name: admin
      email: admin@example.com
    global-operation-parameters: # 全局参数
      - name: Token
        description: 用户信息
        modelRef: String
        parameterType: header
        required: true
        # 默认值只是方便本地开发时，少填参数，生产环境请禁用swagger或者禁用默认参数
        defaultValue: "test"
      - name: Authorization
        description: 客户端信息
        modelRef: String
        parameterType: header
        required: true
        defaultValue: "bGFtcF93ZWI6bGFtcF93ZWJfc2VjcmV0"
      - name: ApplicationId
        description: 应用ID
        modelRef: String
        parameterType: header
        required: true
        defaultValue: "1"


springdoc:
  # 默认是false，需要设置为true
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    # @lamp.generator auto insert springdoc.groupconfigs
    - group: 'oauth_auth'
      displayName: '认证服务'
      paths-to-match: '/**'
      packages-to-scan: com.dalio.cloud.oauth
    - group: 'base_base'
      displayName: 'base-基础模块'
      paths-to-match: '/**'
      packages-to-scan: com.dalio.cloud.base
    - group: 'base_file'
      paths-to-match: '/**'
      displayName: 'base-文件模块'
      packages-to-scan: com.dalio.cloud.file
    - group: 'base_msg'
      paths-to-match: '/**'
      displayName: 'base-消息模块'
      packages-to-scan:
        - com.dalio.cloud.msg
        - com.dalio.cloud.sms
    - group: 'system'
      displayName: '系统管理'
      paths-to-match: '/**'
      packages-to-scan: com.dalio.cloud.system.controller
    - group: 'generator'
      displayName: '代码生成器'
      paths-to-match: '/**'
      packages-to-scan:
        - com.dalio.cloud.generator
        - com.dalio.cloud.test.controller

