lamp:
  generator:
    outputDir: /data/projects/lamp-cloud
    frontOutputDir: /data/projects/lamp-web
    frontSoyOutputDir: /data/projects/lamp-web-pro-soybean
    frontVben5OutputDir: /data/projects/lamp-web-vben-max/apps/web-antd
    # 作者
    author: admin
    # 默认项目
    projectType: BOOT
  system:
    # 演示环境启用
    notAllowWrite: true
  log:
    ipv4:
      enabled: true
      xdbPath: file:/data_prod/target/ip2region_v4.xdb
    ipv6:
      enabled: true
      xdbPath: file:/data_prod/target/ip2region_v6.xdb

server:
  port: 28760