lamp:
  cache:
    type: REDIS
  redis:
    ip: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:16379}
    password: ${REDIS_PASSWORD:SbtyMveYNfLzTks7H0apCmyStPzWJqjy}
    database: 7

spring:
  cache:
    type: GENERIC
  data:
    redis:
      host: ${lamp.redis.ip}
      password: ${lamp.redis.password}
      port: ${lamp.redis.port}
      database: ${lamp.redis.database}
